@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Mar 21 11:55:21 +0530 2024
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 8b647c291ebe4ab8ac166600d14368c7 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_LUT_16_7_behav xil_defaultlib.TB_LUT_16_7 -log elaborate.log"
call xelab  -wto 8b647c291ebe4ab8ac166600d14368c7 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_LUT_16_7_behav xil_defaultlib.TB_LUT_16_7 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
