# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/vihangamuthumala/Documents/project_8_saved/project_8_saved.cache/wt [current_project]
set_property parent.project_path /home/vihangamuthumala/Documents/project_8_saved/project_8_saved.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/vihangamuthumala/Downloads/project_8/AU.vhd
  /home/vihangamuthumala/Downloads/project_8/FA.vhd
  /home/vihangamuthumala/Downloads/project_8/HA.vhd
  /home/vihangamuthumala/Documents/project_8_saved/project_8_saved.srcs/sources_1/new/LUT_16_7.vhd
  /home/vihangamuthumala/Downloads/project_8/RCA_4.vhd
  /home/vihangamuthumala/Downloads/project_8/Reg.vhd
  /home/vihangamuthumala/Downloads/project_8/Slow_Clk.vhd
  /home/vihangamuthumala/Documents/project_8_saved/project_8_saved.srcs/sources_1/new/AU_7_seg.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/vihangamuthumala/Downloads/project_8/Basys3Labs.xdc
set_property used_in_implementation false [get_files /home/vihangamuthumala/Downloads/project_8/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top AU_7_seg -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AU_7_seg.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AU_7_seg_utilization_synth.rpt -pb AU_7_seg_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
