webtalk_init -webtalk_dir /home/vihangamuthumala/Documents/my_work/Nano-Processor/project_final/project_final.sim/sim_1/behav/xsim/xsim.dir/TB_Main_Process_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 20 13:24:18 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4e81fd9e-92ef-49a5-a7a3-419c5266f71c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "44cfa6dd40264a9699380bccba51978d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "76" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Athlon Gold 3150U with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2031.654 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "25" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "39 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "7 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "108" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "65" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "199944_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3441718694 -regid "" -xml /home/vihangamuthumala/Documents/my_work/Nano-Processor/project_final/project_final.sim/sim_1/behav/xsim/xsim.dir/TB_Main_Process_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/vihangamuthumala/Documents/my_work/Nano-Processor/project_final/project_final.sim/sim_1/behav/xsim/xsim.dir/TB_Main_Process_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/vihangamuthumala/Documents/my_work/Nano-Processor/project_final/project_final.sim/sim_1/behav/xsim/xsim.dir/TB_Main_Process_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
