@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Feb 06 14:40:52 +0530 2024
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 63bc98e0fa174a73bf40b4fbeb4714ba --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Circuit2Sim_behav xil_defaultlib.Circuit2Sim -log elaborate.log"
call xelab  -wto 63bc98e0fa174a73bf40b4fbeb4714ba --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Circuit2Sim_behav xil_defaultlib.Circuit2Sim -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
