set_property PACKAGE_PIN W5 [get_ports Clk_In]
	set_property IOSTANDARD LVCMOS33 [get_ports Clk_In]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports Clk_In]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {Reg_7_Out[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[0]}]
set_property PACKAGE_PIN E19 [get_ports {Reg_7_Out[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[1]}]
set_property PACKAGE_PIN U19 [get_ports {Reg_7_Out[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[2]}]
set_property PACKAGE_PIN V19 [get_ports {Reg_7_Out[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reg_7_Out[3]}]
	
set_property PACKAGE_PIN W18 [get_ports {Equal}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Equal}]
set_property PACKAGE_PIN U15 [get_ports {Greater}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Greater}]
set_property PACKAGE_PIN U14 [get_ports {Less}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Less}]
	
set_property PACKAGE_PIN V14 [get_ports {Log_and_Shift_out[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Log_and_Shift_out[0]}]
set_property PACKAGE_PIN V13 [get_ports {Log_and_Shift_out[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Log_and_Shift_out[1]}]
set_property PACKAGE_PIN V3 [get_ports {Log_and_Shift_out[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Log_and_Shift_out[2]}]
set_property PACKAGE_PIN W3 [get_ports {Log_and_Shift_out[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Log_and_Shift_out[3]}]
	
set_property PACKAGE_PIN P1 [get_ports {Zero_Flag}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Zero_Flag}]
set_property PACKAGE_PIN L1 [get_ports {Overflow_Flag}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Overflow_Flag}]

##7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg_data[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_data[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_data[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_data[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_data[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_data[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_data[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]

set_property PACKAGE_PIN U2 [get_ports {anode[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports {Reset}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Reset}]